version: "3"
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: low_latency_spike_node
    restart: on-failure
    env_file:
      - ../.env
    ports:
      - 3000:3000
    networks:
      - spike-low-latency

networks:
  spike-low-latency:
    name: spike-low-latency
    driver: bridge
